#!/bin/sh

mkdir ./.obj

echo "Compiling as a static library..."

cd src
for CFILE in $(find . -maxdepth 1 -name "*.cpp"); do
	echo "	File: $CFILE"
	g++ -O2 -std=c++17 -c "$CFILE" -o "../.obj/$CFILE.o" -I"../include" -I"../include/hlib"

	if [ $? -ne 0 ]; then
        echo "Compilation failed"
        exit 1
    fi
done

echo "Linking..."
cd ..

ar rcs libhotch.a $(find ./.obj -maxdepth 1 -name "*.o")

if [ $? -ne 0 ]; then
	echo "Linking failed"
    exit 1
fi
